### ISSUE TITLE
Example Error: Unable to upload file

### ISSUE THREAD

**Issue by Mjunior1** [LPology/Simple-Ajax-Uploader#161]
Hello,

With his example, I am unable to upload the file.

Already changed the path to the path of my directory but the error message is always the same, how to fix?

**Comment by LPology** [comment]
Post the code you're using. What error message you receiving? 

Set the `debug` option to `true` to see the response from the server in the console. What does it say?

**Comment by Mjunior1** [comment]
I'm using the same code that comes in your examples directory.

I just changed the path of the file to file_upload.php:

$upload_dir = '/images/';

Only ... And come the error message:

"Unable to upload file"

**Comment by LPology** [comment]
What is the response from the server? What is the response code?

**Comment by Mjunior1** [comment]
I'm not a programmer, you could tell me how to get this information? I'm just using your example to be able to add in a job of my code. As I said earlier, I only changed the arquivp file_upload.php

`$ Upload_dir = '/ images /';`

And the following error occurs on the screen:

https://s23.postimg.org/tprimbwvf/error.png

**Comment by Mjunior1** [comment]
I attached my code as an example, you can tell me where I am wrong to not be able to upload?

[](http://rifaverde.com.br/example.zip)

**Comment by LPology** [comment]
In the index.html file, add this line to your plugin settings under the line `button: btn,` (line 55):

```javascript
debug: true,
```

So that it looks like this:

```javascript
button: btn,
debug: true,
```

This options turns on the debugging feature of the plugin so that data about uploads is displayed in the browser console.

In your browser, press F12 and find the "Console". Attempt a file upload. There should be information that appears in the console with "[Uploader]" in front of it. Copy and paste all of that info please.

**Comment by Mjunior1** [comment]
Perfect!! The bar has to be inverted.

Eg: `'\files\Uploader.php'`

Very thanks
