### ISSUE TITLE
setOptions({multiple:true}) only sends first image

### ISSUE THREAD

**Issue by brainvial** [LPology/Simple-Ajax-Uploader#63]

**Comment by LPology** [comment]
To change `multiple` from `false` to `true` you also need to set the `maxUploads` option to a value of greater than 1.

The reason is that in order to enforce single uploads, the `maxUploads` option is set to 1 if `multiple` is `false`:

https://github.com/LPology/Simple-Ajax-Uploader/blob/master/SimpleAjaxUploader.js#L589

```javascript
    if ( this._opts.multiple === false ) {
        this._opts.maxUploads = 1;
    }
```
